title = "Gitleaks Configuration"
description = "Configuration personnalisée pour ignorer les dossiers générés en CI/CD"

[allowlist]
  description = "Ignorer les répertoires de cache et build"
  paths = [
    ".dc-data",
    ".trivy-cache",
    "target",
    "app-logs"
  ]
